name: BusNusantara Feature Update

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
      - '!main'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: |
          echo "sdk.dir=$HOME/Android/Sdk" > local.properties
          echo "API_KEY=\"${{ secrets.API_KEY }}\"" >> gradle.properties
          bash ./gradlew test --stacktrace
